
image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 8090
#     onOpen: open-preview
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
# tasks:
# - init: npm i -g @quasar/cli prettier @vue/cli # runs during prebuild
#   command: yarn
# - command: yarn
tasks:
  - command: az login -u $AZ_USER -p $AZ_PASS; aws sts get-caller-identity; KEY_FILE_NAME=gcp_service_account_key_file.json && echo $GCP_KEY_FILE > ~/.$KEY_FILE_NAME && gcloud auth activate-service-account $GCP_SERVICE_ACCOUNT --key-file=/home/gitpod/.$KEY_FILE_NAME

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - github.vscode-pull-request-github
    - hashicorp.terraform
